### ISSUE TITLE
[Enhancement] API interface / parameter refactor

### ISSUE THREAD

**Issue by atlasstrategic** [HanjoStudy/quantec#3]
Let's review the parameters sent to the API.  These changes will simplify the `quantec_get_data` function, and make `start_year` and `end_year` optional.

## The API interface

The package currently provides an interface to the [Quantec EasyData ](https://www.easydata.co.za/) data API. The function `quantec_get_data` has the following options:

- `time_series_codes` time series to return, string of comma separate of code(s) `NMS-EC_BUS,NMS-GA_BUS`
- `freq` frequency to return `M`, `Q` or `A`
- `start_year` (optional) year to start, string e.g `2001`
- `end_year` (optional) year to end, string e.g. `2020`
- ~~`respformat` to return `csv` or `json`~~
- `log_file` log file to output to
- ~~`is_tidy` tidyformat for easy read~~

## Todo
- [x] Update README.
- [x] Default API params: `startYear = ''`, `endYear = ''`.
- [x] Remove params `is_tidy` and `resp_format`, add defaults to API `isTidy=TRUE` and `respFormat='csv'`.

**Comment by HanjoStudy** [comment]
Great! Both the R and [python](https://github.com/Bureau-for-Economic-Research/quantec-python) has been updated to reflect the changes.

Thanks 🫡
